### ISSUE TITLE
chi_pubhealth spider is broken

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#203]
Here is the error from ```scrapy crawl chi_pubhealth```

```
[scrapy.core.scraper] ERROR: Spider error processing <GET https://www.cityofchicago.org/city/en/depts/cdph/supp_info/boh/2017-board-of-health.html> (referer: None)
Traceback (most recent call last):
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/Users/aweia/projects/documenters-aggregator/documenters_aggregator/spiders/chi_pubhealth.py", line 33, in parse
    parts = re.match(r'(\d{4}) (.*?)s', title)
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

Working on this issue would familiarize you with our spider infrastructure and working with scrapy.

**Comment by jim** [comment]
I am working on this one. Looks like the website received a substantial update, in addition to the spider having the year `2017` hard coded in a few places.

**Comment by r-wei** [comment]
superceded by #258
