### ISSUE TITLE
ValueError parsing start date and time for chi_teacherpension spider

### ISSUE THREAD

**Issue by rebecca-burwei** [City-Bureau/city-scrapers#433]
Running `scrapy crawl chi_teacherpension` gives the following error:

```
Traceback (most recent call last):
  File "~/.virtualenvs/documenters-aggregator/lib/python3.4/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "~/.virtualenvs/documenters-aggregator/lib/python3.4/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "~/.virtualenvs/documenters-aggregator/lib/python3.4/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "~/.virtualenvs/documenters-aggregator/lib/python3.4/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "~/.virtualenvs/documenters-aggregator/lib/python3.4/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "~/repos/city-scrapers/city_scrapers/spiders/chi_teacherpension.py", line 33, in parse
    'start': self._parse_start(response, date, i),
  File "~/repos/city-scrapers/city_scrapers/spiders/chi_teacherpension.py", line 92, in _parse_start
    date = datetime.strptime(date, '%A, %B %d, %Y')
  File "/usr/lib/python3.4/_strptime.py", line 500, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data 'Technology Committee meetings are held in the afternoon. Specific times will be noted in the agenda.' does not match format '%A, %B %d, %Y'
```

Looks like the spider is expecting to parse some dates, but finding text instead.

**Comment by ab1470** [comment]
I'm working on it.
